FROM nginx:alpine
LABEL org.opencontainers.image.source=https://github.com/sikalabs/sikalabs-container-images
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./SD23_white_on_yellow.png /usr/share/nginx/html/SD23_white_on_yellow.png
