FROM nginx:alpine
LABEL org.opencontainers.image.source=https://github.com/sikalabs/sikalabs-container-images
COPY ./index.html /usr/share/nginx/html/index.html
COPY ./RGD23_white_on_brown.png /usr/share/nginx/html/RGD23_white_on_brown.png
