ARG BASE_IMAGE
FROM $BASE_IMAGE
LABEL org.opencontainers.image.source "https://github.com/sikalabs/sikalabs-container-images"
COPY ./themes/sikalabs /opt/bitnami/keycloak/themes/sikalabs
COPY ./themes/ondrejsika /opt/bitnami/keycloak/themes/ondrejsika
COPY ./themes/sika-io /opt/bitnami/keycloak/themes/sika-io
COPY ./themes/sikademo /opt/bitnami/keycloak/themes/sikademo
COPY ./themes/rails /opt/bitnami/keycloak/themes/rails
COPY ./themes/edualf /opt/bitnami/keycloak/themes/edualf
COPY ./themes/integritty /opt/bitnami/keycloak/themes/integritty
COPY ./themes/forclassmates /opt/bitnami/keycloak/themes/forclassmates
COPY ./themes/eventlook /opt/bitnami/keycloak/themes/eventlook
COPY ./themes/mirandamedia /opt/bitnami/keycloak/themes/mirandamedia
COPY ./themes/training /opt/bitnami/keycloak/themes/training
COPY ./themes/mstp /opt/bitnami/keycloak/themes/mstp
COPY ./themes/forendors /opt/bitnami/keycloak/themes/forendors
