ARG BASE_IMAGE=debian:11-slim
FROM $BASE_IMAGE
COPY ./themes/sikalabs /opt/bitnami/keycloak/themes/sikalabs
COPY ./themes/ondrejsika /opt/bitnami/keycloak/themes/ondrejsika
COPY ./themes/sika-io /opt/bitnami/keycloak/themes/sika-io
