name: Build & Publish Docker Images

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  sikalabs--ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ondrejsika -p ${{ secrets.DOCKERHUB_ONDREJSIKA_PASSWORD }}
    - name: Build & Push the Docker Images
      run: cd ci && make all

  sikalabs--kubectl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ondrejsika -p ${{ secrets.DOCKERHUB_ONDREJSIKA_PASSWORD }}
    - name: Build & Push the Docker Images
      run: cd kubectl && make all

  sikalabs--pause:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ondrejsika -p ${{ secrets.DOCKERHUB_ONDREJSIKA_PASSWORD }}
    - name: Build & Push the Docker Images
      run: cd pause && make all

  sikalabs--nginx-public:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ondrejsika -p ${{ secrets.DOCKERHUB_ONDREJSIKA_PASSWORD }}
    - name: Build & Push the Docker Images
      run: cd nginx-public && make all

  sikalabs--debug-server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ondrejsika -p ${{ secrets.DOCKERHUB_ONDREJSIKA_PASSWORD }}
    - name: Build & Push the Docker Images
      run: cd debug-server && make all

  sikalabs--extra--node-with-statica:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ondrejsika -p ${{ secrets.DOCKERHUB_ONDREJSIKA_PASSWORD }}
    - name: Build & Push the Docker Images
      run: cd extra/node-with-statica && make all

  sikalabs--extra--deckschrubber:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ondrejsika -p ${{ secrets.DOCKERHUB_ONDREJSIKA_PASSWORD }}
    - name: Build & Push the Docker Images
      run: cd extra/deckschrubber && make all
